'-----------------------------------------------------------------------
' <copyright company="${CompanyName}">
'     ${CopyrightShort}
' </copyright>
'-----------------------------------------------------------------------
'
'-----------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behaviour and will be lost
'     if the code is regenerated.
' </auto-generated>
'-----------------------------------------------------------------------

Imports System.Reflection;
Imports System.Runtime.InteropServices;

'
' THIS IS A GENERATED FILE. DO NOT MAKE CHANGES IN THIS FILE BECAUSE ANY
' CHANGES WILL BE UNDONE THE NEXT TIME THE FILE IS GENERATED!
'

' General Information about an assembly is controlled through the following
' set of attributes. Change these attribute values to modify the information
' associated with an assembly.
<Assembly: AssemblyCompany("${CompanyName}")>

' The copyright
<Assembly: AssemblyCopyright("${CopyrightLong}")>
