//-----------------------------------------------------------------------
// <copyright company="${CompanyName}">
//     Copyright (c) ${CompanyName}. All rights reserved.
// </copyright>
//-----------------------------------------------------------------------
//
//-----------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost
//     if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------

using System.Runtime.CompilerServices;

/*
 * THIS IS A GENERATED FILE. DO NOT MAKE CHANGES IN THIS FILE BECAUSE ANY
 * CHANGES WILL BE UNDONE THE NEXT TIME THE FILE IS GENERATED! 
 */

${InternalsVisibleToAttributes}