'-----------------------------------------------------------------------
' <copyright company="${CompanyName}">
'     ${CopyrightShort}
' </copyright>
'-----------------------------------------------------------------------
'
'-----------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behaviour and will be lost
'     if the code is regenerated.
' </auto-generated>
'-----------------------------------------------------------------------

Imports System.Diagnostics.CodeAnalysis
Imports System.Reflection
Imports Nuclei.Build

'
' THIS IS A GENERATED FILE. DO NOT MAKE CHANGES IN THIS FILE BECAUSE ANY
' CHANGES WILL BE UNDONE THE NEXT TIME THE FILE IS GENERATED!
'

' The build configuration (e.g. debug/release)
<Assembly: AssemblyConfiguration("${Configuration}")>

' The time the assembly was build
<Assembly: AssemblyBuildTime("${Now}")>

' The version from which the assembly was build
<Module: SuppressMessage( _
    "Microsoft.Usage", _
    "CA2243:AttributeStringLiteralsShouldParseCorrectly", _
    Justification:= "It's a VCS revision, not a version")>
<Assembly: AssemblyBuildInformation(${VersionBuild}, "${VcsRevision}")>