'-----------------------------------------------------------------------
' <copyright company="${CompanyName}">
'     ${CopyrightShort}
' </copyright>
'-----------------------------------------------------------------------
'
'-----------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behaviour and will be lost
'     if the code is regenerated.
' </auto-generated>
'-----------------------------------------------------------------------

Imports System.Reflection

'
' THIS IS A GENERATED FILE. DO NOT MAKE CHANGES IN THIS FILE BECAUSE ANY
' CHANGES WILL BE UNDONE THE NEXT TIME THE FILE IS GENERATED!
'

' Version information for an assembly consists of the following four values:
'      Major Version
'      Minor Version
'      Build Number
'      Revision
' You can specify all the values or you can default the Build and Revision Numbers
' by using the '*' as shown below:
' <Assembly: AssemblyVersion("1.0.*")>
<Assembly: AssemblyVersion("${VersionAssembly}")>
<Assembly: AssemblyFileVersion("${VersionAssemblyFile}")>

' The AssemblyInformationalVersion stores the version that will be displayed in
' Windows explorer.
<Assembly: AssemblyInformationalVersion("${VersionProduct}")>
