'-----------------------------------------------------------------------
' <copyright company="${CompanyName}">
'     ${CopyrightShort}
' </copyright>
'-----------------------------------------------------------------------
'
'-----------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behaviour and will be lost
'     if the code is regenerated.
' </auto-generated>
'-----------------------------------------------------------------------

Imports System.CodeDom.Compiler;

Namespace ${ProductNamespace}.Internals
    ''' <summary>
    ''' Stores marketing information about the company.
    ''' </summary>
    [GeneratedCode("nBuildKit.MsBuild.TemplateFile", "${VersionNBuildKit}")]
    Friend Class CompanyInformation
        ''' <summary>
        ''' The name of the company.
        ''' </summary>
        Public Const CompanyName As String = "${CompanyName}";

        ''' <summary>
        ''' The name of the path in the file system related to the company name.
        ''' </summary>
        Public const CompanyNameInFilePath As String = "${CompanyNameInFilePath}";

        ''' <summary>
        ''' The URL of the main website of the company.
        ''' </summary>
        Public Const CompanyUrl As String = "${CompanyUrl}";
    End Class
End Namespace
