//-----------------------------------------------------------------------
// <copyright company="${CompanyName}">
//     Copyright (c) ${CompanyName}. All rights reserved.
// </copyright>
//-----------------------------------------------------------------------
//
//-----------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behaviour and will be lost
//     if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------

using System.CodeDom.Compiler;

namespace ${ProductNamespace}.Internals
{
    /// <summary>
    /// Stores marketing information about the product.
    /// </summary>
    [GeneratedCode("nBuildKit.MsBuild.TemplateFile", "${VersionNBuildKit}")]
    internal static class ProductInformation
    {
        /// <summary>
        /// The marketing name of the product of which the current assembly is part.
        /// </summary>
        public const string ProductName = "${ProductName}";

        /// <summary>
        /// The name of the path in the file system related to the product name.
        /// </summary>
        public const string ProductNameInFilePath = "${ProductNameInFilePath}";
    }
}