//-----------------------------------------------------------------------
// <copyright company="P. van der Velde">
//     Copyright (c) - P. van der Velde. All rights reserved.
// </copyright>
//-----------------------------------------------------------------------
//
//-----------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behaviour and will be lost
//     if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------

using System.Reflection;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyCompany("P. van der Velde")]

// The copyright
[assembly: AssemblyCopyright("Copyright (c) - P. van der Velde 2014 - 2015. All rights reserved.")]
