//-----------------------------------------------------------------------
// <copyright company="TheNucleus">
// Copyright (c) TheNucleus. All rights reserved.
// Licensed under the Apache License, Version 2.0 license. See LICENCE.md file in the project root for full license information.
// </copyright>
//-----------------------------------------------------------------------

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
                
namespace NBuildKit.MsBuild.Tasks.Nuclei.ExceptionHandling
{
    /// <summary>
    /// Defines a set of event category types used to indicate what category
    /// an event log entry belongs to.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Nuclei.ExceptionHandling", "")]
    internal enum EventType
    {
        /// <summary>
        /// The event log entry belongs to the exception category.
        /// </summary>
        Exception,
    }
}

